# Generated by Django 2.1.1 on 2018-09-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gmoji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('image_url', models.CharField(default='', max_length=100)),
                ('config', models.CharField(default='', max_length=1000)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
